// generated by the @nuxtjs/tailwindcss <https://github.com/nuxt-modules/tailwindcss> module at 6/7/2025, 22:31:35
import "@nuxtjs/tailwindcss/config-ctx"
import configMerger from "@nuxtjs/tailwindcss/merger";

import cfg2 from "./../../tailwind.config.js";
const config = [
{"content":{"files":["E:/Projectos Programacion/appMontiel/dashboard/components/**/*.{vue,js,jsx,mjs,ts,tsx}","E:/Projectos Programacion/appMontiel/dashboard/components/global/**/*.{vue,js,jsx,mjs,ts,tsx}","E:/Projectos Programacion/appMontiel/dashboard/components/**/*.{vue,js,jsx,mjs,ts,tsx}","E:/Projectos Programacion/appMontiel/dashboard/layouts/**/*.{vue,js,jsx,mjs,ts,tsx}","E:/Projectos Programacion/appMontiel/dashboard/plugins/**/*.{js,ts,mjs}","E:/Projectos Programacion/appMontiel/dashboard/composables/**/*.{js,ts,mjs}","E:/Projectos Programacion/appMontiel/dashboard/utils/**/*.{js,ts,mjs}","E:/Projectos Programacion/appMontiel/dashboard/pages/**/*.{vue,js,jsx,mjs,ts,tsx}","E:/Projectos Programacion/appMontiel/dashboard/{A,a}pp.{vue,js,jsx,mjs,ts,tsx}","E:/Projectos Programacion/appMontiel/dashboard/{E,e}rror.{vue,js,jsx,mjs,ts,tsx}","E:/Projectos Programacion/appMontiel/dashboard/app.config.{js,ts,mjs}"]}},
{},
cfg2
].reduce((acc, curr) => configMerger(acc, curr), {});

const resolvedConfig = config;

export default resolvedConfig;