// generated by the @nuxtjs/tailwindcss <https://github.com/nuxt-modules/tailwindcss> module at 06/07/2025, 13:18:56
import "@nuxtjs/tailwindcss/config-ctx"
import configMerger from "@nuxtjs/tailwindcss/merger";

import cfg2 from "./../../tailwind.config.js";
const config = [
{"content":{"files":["C:/Users/M/Desktop/dashboard/components/**/*.{vue,js,jsx,mjs,ts,tsx}","C:/Users/M/Desktop/dashboard/components/global/**/*.{vue,js,jsx,mjs,ts,tsx}","C:/Users/M/Desktop/dashboard/components/**/*.{vue,js,jsx,mjs,ts,tsx}","C:/Users/M/Desktop/dashboard/layouts/**/*.{vue,js,jsx,mjs,ts,tsx}","C:/Users/M/Desktop/dashboard/plugins/**/*.{js,ts,mjs}","C:/Users/M/Desktop/dashboard/composables/**/*.{js,ts,mjs}","C:/Users/M/Desktop/dashboard/utils/**/*.{js,ts,mjs}","C:/Users/M/Desktop/dashboard/pages/**/*.{vue,js,jsx,mjs,ts,tsx}","C:/Users/M/Desktop/dashboard/{A,a}pp.{vue,js,jsx,mjs,ts,tsx}","C:/Users/M/Desktop/dashboard/{E,e}rror.{vue,js,jsx,mjs,ts,tsx}","C:/Users/M/Desktop/dashboard/app.config.{js,ts,mjs}"]}},
{},
cfg2
].reduce((acc, curr) => configMerger(acc, curr), {});

const resolvedConfig = config;

export default resolvedConfig;